// Generated by gencpp from file wot_pkg/is_hit.msg
// DO NOT EDIT!


#ifndef WOT_PKG_MESSAGE_IS_HIT_H
#define WOT_PKG_MESSAGE_IS_HIT_H

#include <ros/service_traits.h>


#include <wot_pkg/is_hitRequest.h>
#include <wot_pkg/is_hitResponse.h>


namespace wot_pkg
{

struct is_hit
{

typedef is_hitRequest Request;
typedef is_hitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct is_hit
} // namespace wot_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wot_pkg::is_hit > {
  static const char* value()
  {
    return "8c3518b3cea1613b70e7336af9bd5db1";
  }

  static const char* value(const ::wot_pkg::is_hit&) { return value(); }
};

template<>
struct DataType< ::wot_pkg::is_hit > {
  static const char* value()
  {
    return "wot_pkg/is_hit";
  }

  static const char* value(const ::wot_pkg::is_hit&) { return value(); }
};


// service_traits::MD5Sum< ::wot_pkg::is_hitRequest> should match
// service_traits::MD5Sum< ::wot_pkg::is_hit >
template<>
struct MD5Sum< ::wot_pkg::is_hitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wot_pkg::is_hit >::value();
  }
  static const char* value(const ::wot_pkg::is_hitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wot_pkg::is_hitRequest> should match
// service_traits::DataType< ::wot_pkg::is_hit >
template<>
struct DataType< ::wot_pkg::is_hitRequest>
{
  static const char* value()
  {
    return DataType< ::wot_pkg::is_hit >::value();
  }
  static const char* value(const ::wot_pkg::is_hitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wot_pkg::is_hitResponse> should match
// service_traits::MD5Sum< ::wot_pkg::is_hit >
template<>
struct MD5Sum< ::wot_pkg::is_hitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wot_pkg::is_hit >::value();
  }
  static const char* value(const ::wot_pkg::is_hitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wot_pkg::is_hitResponse> should match
// service_traits::DataType< ::wot_pkg::is_hit >
template<>
struct DataType< ::wot_pkg::is_hitResponse>
{
  static const char* value()
  {
    return DataType< ::wot_pkg::is_hit >::value();
  }
  static const char* value(const ::wot_pkg::is_hitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WOT_PKG_MESSAGE_IS_HIT_H
